name: spc_build
on: 
    push:
        branches:
            - main
jobs:
    buildwith17:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: setup_java17
              uses: actions/setup-java@v4
              with:
                java-version: 17
                istribution: 'temurin'
                cache: maven
            - name: build_spc
              run: mvn clean package



