name: spc_build
on: 
    push:
        branches:
            - main
jobs:
    buildwith17:
        runs-on: ubuntu-latest
        steps:
            - name: maven
            - uses: actions/checkout@v4
              run: mvn clean package



